name: Build

on:
  push:
    tags:
      - '*'  # Will run when any tag is pushed

jobs:
  build_wheels:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Build wheels
        run: pip wheel --no-deps .
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/*.whl

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: build_wheels
    environment:
      name: publish
      url: https://pypi.org/p/revolve2-robohat
    permissions:
      id-token: write
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
